import type { Brand } from "./types";

// Mock data — replace with API / DB calls later.
export const mockBrands: Brand[] = [
  {
    id: "brd_001",
    name: "Bashundhara Cement",
    slug: "bashundhara-cement",
    website: "https://bashundharacement.com",
    description: "Leading cement manufacturer in Bangladesh.",
    status: "active",
    productCount: 12,
    createdAt: "2026-01-12T09:30:00.000Z",
  },
  {
    id: "brd_002",
    name: "BSRM Steel",
    slug: "bsrm-steel",
    website: "https://bsrm.com",
    description: "Steel rods and structural steel products.",
    status: "active",
    productCount: 8,
    createdAt: "2026-01-20T11:00:00.000Z",
  },
  {
    id: "brd_003",
    name: "RAK Ceramics",
    slug: "rak-ceramics",
    website: "https://rakceramics.com",
    description: "Tiles, sanitaryware and faucets.",
    status: "active",
    productCount: 45,
    createdAt: "2026-02-03T14:15:00.000Z",
  },
  {
    id: "brd_004",
    name: "Berger Paints",
    slug: "berger-paints",
    website: "https://bergerbd.com",
    description: "Interior and exterior paints.",
    status: "active",
    productCount: 30,
    createdAt: "2026-02-18T08:45:00.000Z",
  },
  {
    id: "brd_005",
    name: "Akij Cement",
    slug: "akij-cement",
    website: "https://akijcement.com",
    status: "inactive",
    productCount: 0,
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "brd_006",
    name: "Partex Furniture",
    slug: "partex-furniture",
    website: "https://partexfurniture.com",
    description: "Home and office furniture.",
    status: "active",
    productCount: 22,
    createdAt: "2026-03-14T12:30:00.000Z",
  },
  {
    id: "brd_007",
    name: "Walton",
    slug: "walton",
    website: "https://waltonbd.com",
    description: "Electronics and home appliances.",
    status: "active",
    productCount: 64,
    createdAt: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "brd_008",
    name: "Nasir Glass",
    slug: "nasir-glass",
    status: "inactive",
    productCount: 3,
    createdAt: "2026-04-22T16:20:00.000Z",
  },
  {
    id: "brd_009",
    name: "Seven Rings Cement",
    slug: "seven-rings-cement",
    website: "https://sevenringscement.com",
    status: "active",
    productCount: 5,
    createdAt: "2026-05-05T07:10:00.000Z",
  },
  {
    id: "brd_010",
    name: "GPH Ispat",
    slug: "gph-ispat",
    website: "https://gphispat.com.bd",
    description: "Steel billets and rebar.",
    status: "active",
    productCount: 9,
    createdAt: "2026-05-19T13:40:00.000Z",
  },
  {
    id: "brd_011",
    name: "Elite Paint",
    slug: "elite-paint",
    status: "inactive",
    productCount: 0,
    createdAt: "2026-06-08T10:25:00.000Z",
  },
  {
    id: "brd_012",
    name: "Hatil",
    slug: "hatil",
    website: "https://hatil.com",
    description: "Premium wooden furniture.",
    status: "active",
    productCount: 18,
    createdAt: "2026-07-01T09:55:00.000Z",
  },
];
